# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDHLEpb9twY3UIBvujQGBGIog7lAj2HW
"""

import streamlit as st
import pandas as pd
import re

def procesar_csv(archivo):
    """
    Lee el archivo CSV, extrae los datos con regex y devuelve un DataFrame de pandas.

    Args:
        archivo: Ruta al archivo CSV.

    Returns:
        pandas.DataFrame: DataFrame con los datos procesados.
    """

    datos = []
    with open(archivo, 'r') as f:
        for linea in f:
            # Definimos patrones para cada columna
            patron_precio = r"(\d+\.\d+|\d+)"
            patron_nombres = r"(\w+\s\w+)"
            patron_fecha = r"(\d{2}/\d{2}/\d{2})"
            patron_email = r"(\S+@\S+)"
            patron_telefono = r"\+(\d{2})\s(\d{9})"

            # Extraemos los datos de cada línea usando findall
            resultados = re.findall(f"{patron_precio},{patron_nombres},{patron_nombres},{patron_fecha},{patron_email},{patron_telefono}", linea)

            if resultados:
                datos.append(resultados[0])

    # Creamos un DataFrame de pandas
    df = pd.DataFrame(datos, columns=["Precio", "Nombre_Cliente1", "Nombre_Cliente2", "Fecha", "Email", "Telefono"])
    return df

def main():
    st.title("Procesador de CSV con Regex y Streamlit")

    # Subida de archivo
    uploaded_file = st.file_uploader("Selecciona un archivo CSV", type="csv")

    if uploaded_file is not None:
        # Procesa el archivo
        df = procesar_csv(uploaded_file)

        # Ordenar por columnas (ajusta las columnas según tus necesidades)
        df_ordenado = df.sort_values(by=["Fecha", "Precio"])

        # Descargar el archivo Excel
        st.download_button(
            label="Descargar archivo Excel",
            data=df_ordenado.to_excel(index=False, engine='openpyxl'),
            file_name='datos_procesados.xlsx',
            mime='application/vnd.openpyxl-templates.xlsx'
        )

if __name__ == "__main__":
    main()