# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDHLEpb9twY3UIBvujQGBGIog7lAj2HW
"""

import streamlit as st
import re

def evaluar_contrasena(contrasena):
    """Evalúa la fortaleza de una contraseña y devuelve un mensaje.

    Args:
        contrasena (str): La contraseña a evaluar.

    Returns:
        str: Un mensaje indicando si la contraseña es segura y sugerencias.
    """

    # Patrones para cada tipo de carácter
    patron_mayusculas = re.compile(r'[A-Z]')
    patron_minusculas = re.compile(r'[a-z]')
    patron_numeros = re.compile(r'\d')
    patron_especiales = re.compile(r'[^a-zA-Z0-9]')

    # Verificar longitud y presencia de cada tipo de carácter
    if len(contrasena) >= 8 and \
       patron_mayusculas.search(contrasena) and \
       patron_minusculas.search(contrasena) and \
       patron_numeros.search(contrasena) and \
       patron_especiales.search(contrasena):
        return "¡Excelente! Tu contraseña es muy segura."
    else:
        sugerencias = []
        if len(contrasena) < 8:
            sugerencias.append("La contraseña debe tener al menos 8 caracteres.")
        if not patron_mayusculas.search(contrasena):
            sugerencias.append("Incluye al menos una letra mayúscula.")
        if not patron_minusculas.search(contrasena):
            sugerencias.append("Incluye al menos una letra minúscula.")
        if not patron_numeros.search(contrasena):
            sugerencias.append("Incluye al menos un número.")
        if not patron_especiales.search(contrasena):
            sugerencias.append("Incluye al menos un carácter especial (!, $, #, etc.).")
        return "Tu contraseña podría ser más segura. Considera estas sugerencias:\n" + "\n".join(sugerencias)

# Interfaz de usuario con Streamlit
st.title("Evaluador de Contraseñas")

contrasena = st.text_input("Ingrese su contraseña")

if contrasena:
    resultado = evaluar_contrasena(contrasena)
    st.write(resultado)